#- name: APT install repo key (deb.sury.org)
#  become: yes
#  apt_key:
#    url: https://packages.sury.org/php/apt.gpg
#    state: present
#
#- name: APT add repo (jessie deb.sury.org)
#  become: yes
#  apt_repository: repo={{ item }}
#  with_items:
#    - deb https://packages.sury.org/php/ jessie main

- name: Installs the ppa:ondrej/php repo on Ubuntu systems
  apt_repository:
    repo: ppa:ondrej/php
    update_cache: yes

- name: APT chache update (Repo key added)
  become: yes
  apt: update_cache=yes
