- name: INSTALL base soft (php, modules)
  become: yes
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    #- libcurl4
    - php7.2-fpm
    - php7.2-curl
    - php7.2-mbstring
    - php7.2-xml
    - php7.2-bcmath
    - php7.2-mysql
    - php7.2-zip
    - php7.2-bz2
    - php-soap
    - php7.2-sqlite3
    - php7.2-gd
  notify:
    - Restart php7.2-fpm


# apt-get install --no-install-recommends gcc make libpng-dev
