- name: INSTALL base soft (php, modules)
  become: yes
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    #- libcurl4
    - php7.4-fpm
    - php7.4-curl
    - php7.4-mbstring
    - php7.4-xml
    - php7.4-bcmath
    - php7.4-mysql
    - php7.4-zip
    - php7.4-bz2
    - php-soap
    - php7.4-sqlite3
    - php7.4-gd
  notify:
    - Restart php7.4-fpm


# apt-get install --no-install-recommends gcc make libpng-dev
