- name: Install php7.0
  become: yes
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - php7.0-fpm
    - php7.0-zip
    - php-xml
    - php-curl
    - php7.0-mbstring
    - php-mysql
    - php-bcmath
    - php7.0-intl
  notify:
    - reload php7.0-fpm

- name: Fix pathinfo
  become: yes
  lineinfile: dest=/etc/php/7.0/fpm/php.ini regexp='cgi.fix_pathinfo=' line='cgi.fix_pathinfo=0'
  notify:
    - reload php7.0-fpm
