---
- name: Updating server
  apt:
    update_cache: yes
- name: Installing apt dependencies
  apt:
   name: "{{item}}"
  with_items:
    - python3-pip
    - python3-dev
    - libmysqlclient-dev

- name: Installing pip mysql dependency
  pip:
    name: mysqlclient

- name: Install mysql
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - mysql-server

- name: Start the MySQL service
  action: service name=mysql state=restarted

- name: Create root password
  mysql_user: name=root password={{ mysql_root_password }}

- name: Allow mysql for root
  template: src=root.my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0644

- name: Delete anonymous MySQL server user for "{{ ansible_hostname }}"
  mysql_user: name="root" host="{{ mysql_bind_address }}" password="" state=absent

- name: Bind to ip
  lineinfile:
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: "bind-address"
    line: "bind-address={{ mysql_bind_address }}"

- name: Update mysql root password for all root accounts
  mysql_user: "name=root password={{ mysql_root_password }} priv=*.*:ALL,GRANT host=%"
  notify: restart mysql
