---
- name: Updating server
  apt:
    update_cache: yes

- name: Update server cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install mysql libs
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - python3-pip
    - python3-dev
    - libmysqlclient-dev
    - python3-venv

- name: Create virtual environment
  command: python3 -m venv {{ virtualenv_path }}
  args:
    creates: "{{ virtualenv_path }}/bin/activate"

- name: Install mysqlclient with pip
  pip:
    name: mysqlclient
    virtualenv: "{{ virtualenv_path }}"

- name: Use virtualenv Python for Ansible
  set_fact:
    ansible_python_interpreter: "{{ virtualenv_path }}/bin/python"

- name: Install mysql
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - mysql-server

- name: Start the MySQL service
  action: service name=mysql state=restarted

- name: Create root password
  mysql_user: name=root password={{ mysql_root_password }}

- name: Allow mysql for root
  template: src=root.my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0644

- name: Delete anonymous MySQL server user for "{{ ansible_hostname }}"
  mysql_user: name="root" host="{{ mysql_bind_address }}" password="" state=absent

- name: Bind to ip
  lineinfile:
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: "bind-address"
    line: "bind-address={{ mysql_bind_address }}"

- name: Update mysql root password for all root accounts
  mysql_user: "name=root password={{ mysql_root_password }} priv=*.*:ALL,GRANT host=%"
  notify: restart mysql
