- name: INSTALL base soft (php, modules)
  become: yes
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    #- libcurl4
    - php7.3-fpm
    - php7.3-curl
    - php7.3-mbstring
    - php7.3-xml
    - php7.3-bcmath
    - php7.3-mysql
    - php7.3-zip
    - php7.3-bz2
    - php7.3-sqlite3
    - php7.3-gd
    - php-soap
  notify:
    - Restart php7.3-fpm


# apt-get install --no-install-recommends gcc make libpng-dev
