- name: INSTALL base soft (php, modules)
  become: yes
  apt: name={{ item }} state=present update_cache=yes
  with_items:
#    - libcurl4
#    - php-soap
    - php8.2-fpm
    - php8.2-curl
    - php8.2-mbstring
    - php8.2-xml
    - php8.2-bcmath
    - php8.2-mysql
    - php8.2-zip
    - php8.2-bz2
    - php8.2-sqlite3
    - php8.2-gd
    - php8.2-redis
#  notify:
#    - Restart php8.2-fpm


# apt-get install --no-install-recommends gcc make libpng-dev
