- name: apt install repo key (deb.sury.org)
  when: ansible_os_family == 'Debian'
  become: yes
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present

- name: apt add repo (jessie deb.sury.org)
  when: ansible_os_family == 'Debian'
  become: yes
  apt_repository: repo={{ item }}
  with_items:
    - deb https://packages.sury.org/php/ jessie main

- name: apt chache update (Repo key added)
  become: yes
  apt: update_cache=yes
