- name: INSTALL base soft (php, modules)
  become: yes
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - php7.1-fpm
    - php7.1-curl
    - php7.1-mbstring
    - php7.1-xml
    - php7.1-bcmath
    - php7.1-mysql
  notify:
    - Restart php7.1-fpm
